#
# Apache Guacamole with NGIXN reverse proxy
# For more details see: https://github.com/8gears/containerized-guacamole
# 
version: '3'

services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/docker/containerized-guacamole/conf:/etc/nginx/conf.d
      - /opt/docker/containerized-guacamole/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  init-guac-db:
    image: guacamole/guacamole:latest
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
    volumes:
      - dbinit:/init    

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - dbinit:/docker-entrypoint-initdb.d        
      - /opt/docker/containerized-guacamole/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-guacadb} 
      POSTGRES_PASSWORD: 
    depends_on:
      - init-guac-db

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    volumes:
      - /opt/docker/containerized-guacamole/guacd/rec:/opt/guacamole/rec

  guac:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${POSTGRES_USER:-guacadb} 
      POSTGRES_USER: ${POSTGRES_USER:-guacadb} 
      POSTGRES_PASSWORD:
      VIRTUAL_HOST: 
    depends_on:
      - postgres
      - guacd

volumes:
  dbinit:
